---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "nginx"
  annotations:
    sidecar.istio.io/inject: "false"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "nginx"
    vault.hashicorp.com/agent-inject-secret-dd: "nytm/nirmata/system-credentials/secret/nginx"
    vault.hashicorp.com/agent-inject-template-dd: | {{ with secret "nytm/nirmata/system-credentials/secret/nginx" -}}
  labels:
    nirmata.io/component: "nginx-deployment"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "nginx"
      nirmata.io/component: "nginx-deployment"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        app: "nginx"
        nirmata.io/component: "nginx-deployment"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "nginx"
        image: "nginx:1.7.9"
        command: []
        args: []
        ports:
        - containerPort: 80
          protocol: "TCP"
