# apiVersion: v1
# kind: Namespace
# metadata:
#   name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  minReadySeconds: 0
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 15%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        nirmata.io/component: nginx-deployment
      name: nginx
      annotations:
        sidecar.istio.io/inject: "false"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "nginx"
        vault.hashicorp.com/agent-inject-secret-dd: "nytm/nirmata/system-credentials/secret/nginx"
        vault.hashicorp.com/agent-inject-template-dd: |
          {{ with secret "nytm/nirmata/system-credentials/secret/nginx" -}}
            export DD_API_KEY="{{ .Data.data.api_key }}"
          {{- end }}
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
          protocol: "TCP"