apiVersion: v1

data:

  GUNICORN_THREADS: "10"

  GUNICORN_TIMEOUT: "300"

  GUNICORN_WORKERS: "5"

kind: ConfigMap

metadata:

  labels:

    nirmata.io/application.run: go-app-dev

  name: go-app-configmap-dev

  namespace: go-nonprod

---

apiVersion: v1

kind: Service

metadata:

  labels:

    nirmata.io/application.run: go-app-dev

  name: go-app-dev

  namespace: go-nonprod

spec:

  ports:

  - name: http

    port: 80

    protocol: TCP

    targetPort: 8000

  selector:

    app: go-app

    nirmata.io/application.run: go-app-dev

  type: ClusterIP

---

apiVersion: apps/v1

kind: Deployment

metadata:

  labels:

    nirmata.io/application.run: go-app-dev

  name: go-app-dev

  namespace: go-nonprod

spec:

  selector:

    matchLabels:

      nirmata.io/application.run: go-app-dev

  template:

    metadata:

      labels:

        app: go-app

        nirmata.io/application.run: go-app-dev

    spec:

      containers:

      - env:

        - name: DJANGO_ALLOWED_HOSTS

          value: go-ks.dev.nibr.nirmata.net,go.global.nibr.novartis.net,go.nibr.novartis.net,go.na.novartis.net,go.jp.novartis.net,go.eu.novartis.net,go.ap.novartis.net,go.la.novartis.net

        - name: DJANGO_DEBUG

          value: "True"

        - name: GOAPP_RUNTIME_ENV

          value: dev

        - name: GO_DB_ENGINE

          value: django.db.backends.mysql

        - name: GO_DB_NAME

          value: go_db

        - name: GO_DB_USER

          value: go_user.nirmata.com

        - name: GO_DB_HOST

          value: sharedinnomysql-usnv-test.cq62iv6ojtxz.us-east-1.rds.amazonaws.com

        - name: GO_DB_PORT

          value: "3306"

        - name: GUNICORN_WORKERS

          valueFrom:

            configMapKeyRef:

              key: GUNICORN_WORKERS

              name: go-app-configmap-dev.nirmata.com

        - name: GUNICORN_THREADS

          valueFrom:

            configMapKeyRef:

              key: GUNICORN_THREADS

              name: go-app-configmap-dev

        - name: GUNICORN_TIMEOUT

          valueFrom:

            configMapKeyRef:

              key: GUNICORN_TIMEOUT

              name: go-app-configmap-dev

        envFrom:

        - secretRef:

            name: go-app-secrets

        hostNetwork: false

        image: docker-repo.nibr.novartis.net/go-app:1.0.15-26bdc1b

        imagePullPolicy: IfNotPresent

        name: go-app

        ports:

        - containerPort: 8000

        readinessProbe:

          httpGet:

            path: /:health

            port: 8000

          initialDelaySeconds: 5

          periodSeconds: 5

        resources:

          limits:

            cpu: 250m

            memory: 500Mi

          requests:

            cpu: 250m

            memory: 250Mi

        securityContext:

          allowPrivilegeEscalation: false

          runAsNonRoot: true

---

apiVersion: extensions/v1beta1

kind: Ingress

metadata:

  annotations:

    ingress.kubernetes.io/ssl-redirect: "false"

  labels:

    nirmata.io/application.run: go-app-dev

  name: go-app-ingress-dev

  namespace: go-nonprod

spec:

  rules:

  - host: go

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go-ks.dev.nibr.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.global.nibr.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.nibr.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.na.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.jp.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.eu.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.ap.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  - host: go.la.novartis.net

    http:

      paths:

      - backend:

          serviceName: go-app-dev

          servicePort: 80

        path: /

  tls:

  - hosts:

    - go

    - go-ks.dev.nibr.novartis.net

    - go.na.novartis.net

    - go.jp.novartis.net

    - go.la.novartis.net

    - go.eu.novartis.net

    - go.ap.novartis.net

    - go.global.nibr.novartis.net

    - go.nibr.novartis.net

    secretName: ""
