resources:
- ../.kube.yaml
patchesStrategicMerge:
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
    annotations: {}
    name: "nginx-2"
    labels:
      nirmata.io/component: "nginx-deployment"
